// Exception codes used for service-level exceptions
export enum ServiceExceptionCode {
    // Base
    BASE_INTERNAL_ERROR = "INTERNAL_ERROR",
    BASE_VALIDATION_ERROR = "VALIDATION_ERROR",

    // Trading
    TRADING_GAS_PRICE_FETCH_FAILED = "TRADING_GAS_PRICE_FETCH_FAILED",
    TRADING_FACTORY_CONTRACT_CALL_FAILED = "TRADING_FACTORY_CONTRACT_CALL_FAILED",
    TRADING_PAIR_CONTRACT_CALL_FAILED = "TRADING_PAIR_CONTRACT_CALL_FAILED"
};